{
    "version": "0.1",
    "phases": {
        "install": {
            "runtime-versions": {
                "python": "3.13"
            }
        },
        "build": {
            "commands": [
                "pip install -r requirements.txt -t .",
                "sam build"
            ]
        }
    }
}
